spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hbucvc?serverTimezone=GMT%2B8
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
luck-permission:
  table:
    permission-name: luck_permissionss
    role-name: luck_roless
    role-permission-name: luck_role_perm_ss